/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.practicesummative2;

/**
 *
 * @author chand
 */
public class SetDifficultyPanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    public SetDifficultyPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        easyButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        hardButton = new javax.swing.JButton();
        mediumButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(5000, 500));
        setPreferredSize(new java.awt.Dimension(1055, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        easyButton.setBackground(new java.awt.Color(174, 230, 246));
        easyButton.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        easyButton.setText("<html>&#9829;&#9829;&#9829; Easy</html> ");
        easyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        easyButton.setHideActionText(true);
        easyButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        easyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyButtonActionPerformed(evt);
            }
        });
        add(easyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 1080, 40));

        backButton.setBackground(new java.awt.Color(174, 230, 246));
        backButton.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        backButton.setText("Back");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backButton.setHideActionText(true);
        backButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 1080, 40));

        hardButton.setBackground(new java.awt.Color(174, 230, 246));
        hardButton.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        hardButton.setText("<html>&#9829;&nbsp;&nbsp;&nbsp;Hard </html>");
        hardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hardButton.setHideActionText(true);
        hardButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardButtonActionPerformed(evt);
            }
        });
        add(hardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1080, 40));

        mediumButton.setBackground(new java.awt.Color(174, 230, 246));
        mediumButton.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        mediumButton.setText("<html>&#9829;&#9829;&nbsp;&nbsp;Medium</html>");
        mediumButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mediumButton.setHideActionText(true);
        mediumButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mediumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumButtonActionPerformed(evt);
            }
        });
        add(mediumButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 1080, 40));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TypeBlast.png"))); // NOI18N
        backgroundLabel.setText("High Score:");
        add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void mediumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumButtonActionPerformed
        // TODO add your handling code here:
        // changing the panel and setting up the difficulty
        ParentGamePanel.run(2);
        GameFrame.cl.show(GameFrame.p, "Game Screen");
    }//GEN-LAST:event_mediumButtonActionPerformed

    private void easyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyButtonActionPerformed
        // TODO add your handling code here:
        // changing the panel and setting up the difficulty
        ParentGamePanel.run(3);
        GameFrame.cl.show(GameFrame.p, "Game Screen");
    }//GEN-LAST:event_easyButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        // switching jpanel to go back
        GameFrame.cl.show(GameFrame.p, "Home Screen");
    }//GEN-LAST:event_backButtonActionPerformed

    private void hardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardButtonActionPerformed
        // TODO add your handling code here:
        // changing the panel and setting up the difficulty
        ParentGamePanel.run(1);
        GameFrame.cl.show(GameFrame.p, "Game Screen");
    }//GEN-LAST:event_hardButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton easyButton;
    private javax.swing.JButton hardButton;
    private javax.swing.JButton mediumButton;
    // End of variables declaration//GEN-END:variables
}
