/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.practicesummative2;

/**
 *
 * @author chand
 */
public class GameOverPanel extends javax.swing.JPanel {

    /**
     * Creates new form GameOverPanel
     */
    public GameOverPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quitButton = new javax.swing.JButton();
        restartButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1055, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quitButton.setBackground(new java.awt.Color(174, 230, 246));
        quitButton.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        quitButton.setText("Quit");
        quitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        quitButton.setHideActionText(true);
        quitButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        add(quitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 1080, 40));

        restartButton.setBackground(new java.awt.Color(174, 230, 246));
        restartButton.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        restartButton.setText("Restart");
        restartButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        restartButton.setHideActionText(true);
        restartButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });
        add(restartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1080, 40));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GameOver.png"))); // NOI18N
        add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
        // TODO add your handling code here:
        // changing the panel to previous panel
        GameFrame.cl.show(GameFrame.p, "Difficulty Screen");
    }//GEN-LAST:event_restartButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
        // changing the panel to the home screen
        GameFrame.cl.show(GameFrame.p, "Home Screen");
    }//GEN-LAST:event_quitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton restartButton;
    // End of variables declaration//GEN-END:variables
}
